source 'https://github.com/CocoaPods/Specs.git'

target :CoreTest do
  pod 'NCMB/Core', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end

target :FacebookUtilsTest do
  pod 'NCMB/FacebookUtils', :path => '../'
  pod 'FBSDKCoreKit', '~> 4.1.0'
  pod 'FBSDKLoginKit', '~> 4.1.0'

  pod 'Specta'
  pod 'Expecta'
end

target :GoogleUtilsTest do
  pod 'NCMB/GoogleUtils', :path => '../'
  pod 'Google/SignIn'

  pod 'Specta'
  pod 'Expecta'
end
