target :NCMBTests do
  pod 'NCMB', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  # pod 'OCHamcrest',  '~> 3.0'   # hamcrest matchers
  # pod 'OCMockito',   '~> 1.0'   # OCMock
  # pod 'LRMocky',     '~> 0.9'   # LRMocky
end
