target :NCMB do
    pod 'Facebook-iOS-SDK', '~> 3.23'
end

target :NCMBTest do
  pod 'Specta', '~> 0.5'
  # pod 'Expecta',     '~> 0.3'   # expecta matchers
  # pod 'OCMock',      '~> 2.2'   # OCMock
  # pod 'OCHamcrest',  '~> 3.0'   # hamcrest matchers
  # pod 'OCMockito',   '~> 1.0'   # OCMock
  # pod 'LRMocky',     '~> 0.9'   # LRMocky
end
